name: pet-backend
channels:
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - contourpy=1.3.1
  - cpuonly=2.0
  - cycler=0.11.0
  - expat=2.7.1
  - filelock=3.17.0
  - fonttools=4.55.3
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libpq=17.4
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.4.2
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - packaging=24.2
  - pillow=11.1.0
  - pip=25.1
  - pycparser=2.21
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - requests=2.32.4
  - setuptools=78.1.1
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.50.2
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tomli=2.0.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.1
  - typing_extensions=4.12.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - backports-datetime-fromisoformat==2.0.3
      - blinker==1.9.0
      - cachecontrol==0.14.3
      - cachetools==5.5.2
      - click==8.2.1
      - colorama==0.4.6
      - cryptography==45.0.5
      - dotenv==0.9.9
      - firebase-admin==7.0.0
      - flask==3.1.1
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-cloud-core==2.4.3
      - google-cloud-firestore==2.21.0
      - google-cloud-storage==3.2.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.1
      - grpcio-status==1.73.1
      - h2==4.2.0
      - hpack==4.1.0
      - hyperframe==6.1.0
      - itsdangerous==2.2.0
      - marshmallow==4.0.0
      - msgpack==1.1.1
      - oauthlib==3.3.1
      - proto-plus==1.26.1
      - protobuf==6.31.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyjwt==2.10.1
      - python-dotenv==1.1.1
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - typing-inspection==0.4.1
      - werkzeug==3.1.3
prefix: C:\Users\jeongho\AppData\Local\anaconda3\envs\pet-backend
